"""Impact-selected acceptance planning and execution for QuantResearch."""

from .architecture import validate_test001_admission
from .batch import (
    A0BatchConfig,
    A0BatchSelector,
    A0EvidenceLedger,
    A0Selection,
    BatchEvidenceLedger,
    BatchSelector,
    BatchStatus,
    EvidenceRecord,
    batch_identity,
)
from .cache import ArtifactCache
from .core import (
    AcceptanceFailure,
    AcceptancePlan,
    AcceptanceSelector,
    OwnerContract,
    PlanStep,
    historical_timeout,
)
from .fixtures import AcceptanceSession, SQLiteSession
from .local import (
    FixedBaseProver,
    JsonlEventSink,
    LocalWheelBuilder,
    LocalWheelInstaller,
    build_fixed_base_diff,
    git_source_fingerprint,
)
from .migration import LegacyScopeMigration, migrate_legacy_scope
from .observability import audit_performance
from .research_visibility import (
    DEFAULT_PROTECTION_CLOSURE_BUDGET,
    MAX_PROTECTION_CLOSURE_BUDGET,
    VISIBILITY_DECISION_SCHEMA,
    VISIBILITY_REQUEST_SCHEMA,
    AccessGrant,
    CurrentConsumerAccess,
    FrozenResearchPolicy,
    GateDecision,
    GuardedDelivery,
    HistoricalContextRef,
    LineageScope,
    LogicalScope,
    LogicalTimeRange,
    MaterialVisibilityDecision,
    ResearchMaterial,
    VisibilityGate,
    VisibilityRequest,
    evaluate_visibility_request,
    guard_visibility_delivery,
)
from .runner import (
    InstalledEnvironment,
    PlanRunner,
    ProcessResult,
    RunReceipt,
    SubprocessProcess,
)
from .train import EnvironmentOutcome, GateRequest, ReleaseTrain

__all__ = [
    "DEFAULT_PROTECTION_CLOSURE_BUDGET",
    "MAX_PROTECTION_CLOSURE_BUDGET",
    "VISIBILITY_DECISION_SCHEMA",
    "VISIBILITY_REQUEST_SCHEMA",
    "A0BatchConfig",
    "A0BatchSelector",
    "A0EvidenceLedger",
    "A0Selection",
    "AcceptanceFailure",
    "AcceptancePlan",
    "AcceptanceSelector",
    "AcceptanceSession",
    "AccessGrant",
    "ArtifactCache",
    "BatchEvidenceLedger",
    "BatchSelector",
    "BatchStatus",
    "CurrentConsumerAccess",
    "EnvironmentOutcome",
    "EvidenceRecord",
    "FixedBaseProver",
    "FrozenResearchPolicy",
    "GateDecision",
    "GateRequest",
    "GuardedDelivery",
    "HistoricalContextRef",
    "InstalledEnvironment",
    "JsonlEventSink",
    "LegacyScopeMigration",
    "LineageScope",
    "LocalWheelBuilder",
    "LocalWheelInstaller",
    "LogicalScope",
    "LogicalTimeRange",
    "MaterialVisibilityDecision",
    "OwnerContract",
    "PlanRunner",
    "PlanStep",
    "ProcessResult",
    "ReleaseTrain",
    "ResearchMaterial",
    "RunReceipt",
    "SQLiteSession",
    "SubprocessProcess",
    "VisibilityGate",
    "VisibilityRequest",
    "audit_performance",
    "batch_identity",
    "build_fixed_base_diff",
    "evaluate_visibility_request",
    "git_source_fingerprint",
    "guard_visibility_delivery",
    "historical_timeout",
    "migrate_legacy_scope",
    "validate_test001_admission",
]
