"""Fixture-backed, read-only WebUI shell for the Manager GUI.

The web package owns the shared shell and the S1 page-hook mounts. Later domain
pages can register their own read-only views without changing the transport
envelope or provider boundary from S1-T1.
"""

from .app import ManagerGUIApp, WebRequestState
from .atlas import ATLAS_INTEGRATION_HOOK, render_atlas_view
from .comparison import (
    COMPARISON_INTEGRATION_HOOK,
    COMPARISON_ROUTE,
    render_genome_comparison_view,
)
from .conditions import (
    CONDITIONS_INTEGRATION_HOOK,
    CONDITIONS_ROUTE,
    render_genome_conditions_view,
)
from .documents import (
    ApprovedDirectoryBoundary,
    DocumentIndexState,
    DocumentType,
    SourceDocument,
    SourceDocumentsViewModel,
    render_source_documents_view,
)
from .evidence import (
    EVIDENCE_INTEGRATION_HOOK,
    EVIDENCE_RESOURCE,
    EVIDENCE_ROUTE,
    EvidenceFixtureState,
    build_evidence_fixture,
    evidence_fixture_provider,
    render_evidence_view,
)
from .evidence_comparison import (
    EVIDENCE_COMPARISON_INTEGRATION_HOOK,
    EVIDENCE_COMPARISON_RESOURCE,
    EVIDENCE_COMPARISON_ROUTE,
    EvidenceComparisonFixtureState,
    build_evidence_comparison_fixture,
    evidence_comparison_fixture_provider,
    render_evidence_comparison_view,
)
from .failure_grouping import (
    FAILURE_GROUPING_INTEGRATION_HOOK,
    FAILURE_GROUPING_RESOURCE,
    FAILURE_GROUPING_ROUTE,
    GroupingFixtureState,
    build_failure_grouping_fixture,
    failure_grouping_fixture_provider,
    render_failure_grouping_view,
)
from .failure_patterns import (
    FAILURE_PATTERNS_INTEGRATION_HOOK,
    FAILURE_PATTERNS_RESOURCE,
    MEMORY_FAILURE_INTEGRATION_HOOK,
    MEMORY_FAILURE_RESOURCE,
    render_failure_patterns_view,
    render_memory_failure_view,
)
from .genome import GENOME_INTEGRATION_HOOK, GENOME_ROUTE, render_genome_view
from .history import (
    HISTORY_SCOPES,
    HistoryEvent,
    HistoryEventType,
    HistoryViewModel,
    render_history_view,
)
from .i18n import DEFAULT_LOCALE, Locale, Translator, resolve_locale, with_lang
from .interaction import (
    EXPORT_ENDPOINT,
    EXPORT_SCHEMA,
    current_view_export,
    export_filename,
    export_json,
    export_url,
    opaque_copy_button,
    render_alternative_view,
    render_current_view_export,
    render_export_control,
    render_graph_table_alternative,
    render_view_mode_controls,
)
from .lineage import (
    LINEAGE_INTEGRATION_HOOK,
    LINEAGE_RESOURCE,
    LINEAGE_ROUTE,
    LineageFixtureState,
    build_lineage_fixture,
    lineage_fixture_provider,
    render_lineage_view,
)
from .memory import MEMORY_INTEGRATION_HOOK, render_memory_view
from .methodology import (
    METHODOLOGY_INTEGRATION_HOOK,
    MethodologyCategory,
    MethodologyIndexState,
    MethodologyMethod,
    MethodologyViewModel,
    render_methodology_view,
)
from .navigation import (
    NAVIGATION,
    NavigationItem,
    PageWindow,
    ViewId,
    clear_filters_link,
    context_link,
    query_values,
)
from .portal import (
    PORTAL_INTEGRATION_HOOK,
    PORTAL_RESOURCE,
    REPORT_SOURCE_RESOURCE,
    PortalArtifactState,
    PortalFixtureState,
    PortalViewModel,
    build_portal_fixture,
    render_portal,
    render_portal_view,
)
from .research_story import (
    StoryMode,
    render_research_story,
    render_research_story_view,
)
from .s6_fixtures import S6_FIXTURE_STATES, S6_RESOURCES, build_s6_fixture
from .search import (
    SEARCH_INTEGRATION_HOOK,
    SEARCH_RESOURCE,
    SearchFixtureState,
    SearchHit,
    SearchPagination,
    SearchState,
    SearchViewModel,
    build_search_fixture,
    render_search,
    render_search_view,
    search_result_link,
)
from .server import create_server, run_server
from .status import (
    DISPLAY_STATE_LABELS,
    DisplayState,
    StatusDescriptor,
    describe_status,
    display_state_for,
    render_common_state,
    render_operational_state,
    render_status_block,
)

__all__ = [
    "ATLAS_INTEGRATION_HOOK",
    "COMPARISON_INTEGRATION_HOOK",
    "COMPARISON_ROUTE",
    "CONDITIONS_INTEGRATION_HOOK",
    "CONDITIONS_ROUTE",
    "DEFAULT_LOCALE",
    "DISPLAY_STATE_LABELS",
    "EVIDENCE_COMPARISON_INTEGRATION_HOOK",
    "EVIDENCE_COMPARISON_RESOURCE",
    "EVIDENCE_COMPARISON_ROUTE",
    "EVIDENCE_INTEGRATION_HOOK",
    "EVIDENCE_RESOURCE",
    "EVIDENCE_ROUTE",
    "EXPORT_ENDPOINT",
    "EXPORT_SCHEMA",
    "FAILURE_GROUPING_INTEGRATION_HOOK",
    "FAILURE_GROUPING_RESOURCE",
    "FAILURE_GROUPING_ROUTE",
    "FAILURE_PATTERNS_INTEGRATION_HOOK",
    "FAILURE_PATTERNS_RESOURCE",
    "GENOME_INTEGRATION_HOOK",
    "GENOME_ROUTE",
    "HISTORY_SCOPES",
    "LINEAGE_INTEGRATION_HOOK",
    "LINEAGE_RESOURCE",
    "LINEAGE_ROUTE",
    "MEMORY_FAILURE_INTEGRATION_HOOK",
    "MEMORY_FAILURE_RESOURCE",
    "MEMORY_INTEGRATION_HOOK",
    "METHODOLOGY_INTEGRATION_HOOK",
    "NAVIGATION",
    "PORTAL_INTEGRATION_HOOK",
    "PORTAL_RESOURCE",
    "REPORT_SOURCE_RESOURCE",
    "S6_FIXTURE_STATES",
    "S6_RESOURCES",
    "SEARCH_INTEGRATION_HOOK",
    "SEARCH_RESOURCE",
    "ApprovedDirectoryBoundary",
    "DisplayState",
    "DocumentIndexState",
    "DocumentType",
    "EvidenceComparisonFixtureState",
    "EvidenceFixtureState",
    "GroupingFixtureState",
    "HistoryEvent",
    "HistoryEventType",
    "HistoryViewModel",
    "LineageFixtureState",
    "Locale",
    "ManagerGUIApp",
    "MethodologyCategory",
    "MethodologyIndexState",
    "MethodologyMethod",
    "MethodologyViewModel",
    "NavigationItem",
    "PageWindow",
    "PortalArtifactState",
    "PortalFixtureState",
    "PortalViewModel",
    "SearchFixtureState",
    "SearchHit",
    "SearchPagination",
    "SearchState",
    "SearchViewModel",
    "SourceDocument",
    "SourceDocumentsViewModel",
    "StatusDescriptor",
    "StoryMode",
    "Translator",
    "ViewId",
    "WebRequestState",
    "build_evidence_comparison_fixture",
    "build_evidence_fixture",
    "build_failure_grouping_fixture",
    "build_lineage_fixture",
    "build_portal_fixture",
    "build_s6_fixture",
    "build_search_fixture",
    "clear_filters_link",
    "context_link",
    "create_server",
    "current_view_export",
    "describe_status",
    "display_state_for",
    "evidence_comparison_fixture_provider",
    "evidence_fixture_provider",
    "export_filename",
    "export_json",
    "export_url",
    "failure_grouping_fixture_provider",
    "lineage_fixture_provider",
    "opaque_copy_button",
    "query_values",
    "render_alternative_view",
    "render_atlas_view",
    "render_common_state",
    "render_current_view_export",
    "render_evidence_comparison_view",
    "render_evidence_view",
    "render_export_control",
    "render_failure_grouping_view",
    "render_failure_patterns_view",
    "render_genome_comparison_view",
    "render_genome_conditions_view",
    "render_genome_view",
    "render_graph_table_alternative",
    "render_history_view",
    "render_lineage_view",
    "render_memory_failure_view",
    "render_memory_view",
    "render_methodology_view",
    "render_operational_state",
    "render_portal",
    "render_portal_view",
    "render_research_story",
    "render_research_story_view",
    "render_search",
    "render_search_view",
    "render_source_documents_view",
    "render_status_block",
    "render_view_mode_controls",
    "resolve_locale",
    "run_server",
    "search_result_link",
    "with_lang",
]
