"""Reader v1 UI-only contract; v0 owner/API schemas remain unchanged."""

from .fixtures import (
    READER_FIXTURE_STATES,
    ReaderFixtureProvider,
    ReaderFixtureState,
    build_reader_fixture,
    reader_fixture_provider,
)
from .models import (
    READER_PROJECTION_SCHEMA,
    READER_PROJECTION_VERSION,
    SAMPLE_BANNER_KEY,
    ClaimKind,
    FrozenJSON,
    ProjectionMode,
    ProjectionReference,
    RawSource,
    ReaderAvailability,
    ReaderAvailabilityStatus,
    ReaderClaim,
    ReaderProjection,
    ReaderSummary,
    SampleData,
    TemplateValue,
    project_read_model,
)
from .provider import (
    ReaderProjectionProvider,
    ReaderProvider,
    ReadOnlyReaderProjectionProvider,
    V0ReaderProjectionProvider,
    project_v0,
)
from .schema import READER_PROJECTION_JSON_SCHEMA
from .templates import (
    ReaderSection,
    ReaderTemplates,
    preserve_claim_value,
    preserve_owner_text,
    render_claim_explanation,
    render_derivation,
    render_mode_label,
    render_sample_banner,
    render_section,
    render_source_reference,
    render_summary,
    templates,
)

__all__ = [
    "READER_FIXTURE_STATES",
    "READER_PROJECTION_JSON_SCHEMA",
    "READER_PROJECTION_SCHEMA",
    "READER_PROJECTION_VERSION",
    "SAMPLE_BANNER_KEY",
    "ClaimKind",
    "FrozenJSON",
    "ProjectionMode",
    "ProjectionReference",
    "RawSource",
    "ReadOnlyReaderProjectionProvider",
    "ReaderAvailability",
    "ReaderAvailabilityStatus",
    "ReaderClaim",
    "ReaderFixtureProvider",
    "ReaderFixtureState",
    "ReaderProjection",
    "ReaderProjectionProvider",
    "ReaderProvider",
    "ReaderSection",
    "ReaderSummary",
    "ReaderTemplates",
    "SampleData",
    "TemplateValue",
    "V0ReaderProjectionProvider",
    "preserve_claim_value",
    "preserve_owner_text",
    "render_claim_explanation",
    "render_derivation",
    "render_mode_label",
    "render_sample_banner",
    "render_section",
    "render_source_reference",
    "render_summary",
    "templates",
    "build_reader_fixture",
    "project_read_model",
    "project_v0",
    "reader_fixture_provider",
]
